name: Stock Watch

on:
  workflow_dispatch:

  schedule:
    - cron: '18 3 * * 1-5'   # 北京11:18
    - cron: '40 5 * * 1-5'   # 北京13:40
    - cron: '20 6 * * 1-5'   # 北京14:20
    - cron: '40 6 * * 1-5'   # 北京14:40
    - cron: '50 6 * * 1-5'   # 北京14:50

permissions:
  contents: write

concurrency:
  group: stock-watch
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Chinese Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Install Packages
        run: |
          pip install -r requirements.txt

      - name: Run Stock Script
        run: |
          python stockchoice.py

      - name: Show Generate Time
        run: |
          echo "北京时间：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')"

      - name: Commit Latest Files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add docs/
          git add stock_output/

          git commit -m "Auto update stock page" || echo "No changes"

          git push

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stock_output
          path: stock_output/
