name: stock-watch

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Chinese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run stock script
        run: |
          python stockchoice.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: stock_output
          path: stock_output/
            - name: Build web page
        run: |
          mkdir -p docs
          cp stock_output/stock_watch.html docs/index.html

      - name: Commit docs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add docs/index.html
          git commit -m "update web page" || echo "No changes"

          git push
